language: csharp
dist: trusty
dotnet: 1.0.3
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore ./src/StegoCoreLib/StegoCoreLib.csproj
  - dotnet build ./src/StegoCoreLib/StegoCoreLib.csproj
